import Head from "next/head"
import Footer from "./snippets/footer"
import Header from "./snippets/header"

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>NEXTERCE | OussamaDev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-50 dark:bg-gray-900 min-h-screen text-gray-800 dark:text-gray-50 font-[Poppins]">
        <main className='mx-auto container'>
          <Header />
          <main>{children}</main>
          <Footer />
        </main>
      </div>
    </>
  )
}