import Head from 'next/head'
import ProductCard from '../components/ui/products/card'
import { Hero } from '../components/ui/hero';
import { useSession } from "next-auth/react";
import { getProducts } from '../services';

export default function Home({products}) {  
  return (
    <>
      <Head>
        <title>Nexterce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <div className='flex flex-row flex-wrap justify-center'>
          {products.map(product => <ProductCard key={product.id} product={product} />)}
        </div>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const products = (await getProducts() || [])
  return {
    props: {
      products,
    }
  }
}
