import Script from 'next/script';
import Head from 'next/head'
import ProductCard from '../components/ui/products/card'
import { Hero } from '../components/ui/hero';

export default function Home() {
  return (
    <>
      <Head>
        <title>Nexterce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Hero />
        <ProductCard />
      </main>
    </>
  )
}
